import React from 'react';

export class BButtons extends React.Component< {} > {
    render() {
        return (
            <div>
                <table>
                    <tbody>
                        <tr>
                            <th>
                               V
                            </th>
                            <th>
                               C
                            </th>
                        </tr>
                        <tr>
                            <th>
                               1
                            </th>
                            <th>
                               0
                            </th>
                        </tr>
                        <tr>
                            <th>
                               2
                            </th>
                            <th>
                               1
                            </th>
                        </tr>
                        <tr>
                            <th>
                               3
                            </th>
                            <th>
                               2
                            </th>
                        </tr>
                        <tr>
                            <th>
                               4
                            </th>
                            <th>
                               3
                            </th>
                        </tr>
                        <tr>
                            <th>
                               5
                            </th>
                            <th>
                               4
                            </th>
                        </tr>
                    </tbody>
                </table>
            </div>
        )
    }
}
