export const words = [
    'Hollywood', 'Well', 'Foot', 'New York', 'Spring', 'Court', 'Tube', 'Point', 'Tablet', 'Slip', 'Date', 'Drill',
    'Lemon', 'Bell', 'Screen', 'Fair', 'Torch', 'State', 'Match', 'Iron', 'Block', 'France', 'Australia', 'Limousine',
    'Stream', 'Glove', 'Nurse', 'Leprechaun', 'Play', 'Tooth', 'Arm', 'Bermuda', 'Diamond', 'Whale', 'Comic', 'Mammoth',
    'Green', 'Pass', 'Missile', 'Paste', 'Drop', 'Phoenix', 'Marble', 'Staff', 'Figure', 'Park', 'Centaur', 'Shadow',
    'Fish', 'Cotton', 'Egypt', 'Theater', 'Scale', 'Fall', 'Track', 'Force', 'Dinosaur', 'Bill', 'Mine', 'Turkey',
    'March', 'Contract', 'Bridge', 'Robin', 'Line', 'Plate', 'Band', 'Fire', 'Bank', 'Boom', 'Cat', 'Shot', 'Suit',
    'Chocolate', 'Roulette', 'Mercury', 'Moon', 'Net', 'Lawyer', 'Satellite', 'Angel', 'Spider', 'Germany', 'Fork',
    'Pitch', 'King', 'Crane', 'Trip', 'Dog', 'Conductor', 'Part', 'Bugle', 'Witch', 'Ketchup', 'Press', 'Spine', 'Worm',
    'Alps', 'Bond', 'Pan', 'Beijing', 'Racket', 'Cross', 'Seal', 'Aztec', 'Maple', 'Parachute', 'Hotel', 'Berry',
    'Soldier', 'Ray', 'Post', 'Greece', 'Square', 'Mass', 'Bat', 'Wave', 'Car', 'Smuggler', 'England', 'Crash', 'Tail',
    'Card', 'Horn', 'Capital', 'Fence', 'Deck', 'Buffalo', 'Microscope', 'Jet', 'Duck', 'Ring', 'Train', 'Field',
    'Gold', 'Tick', 'Check', 'Queen', 'Strike', 'Kangaroo', 'Spike', 'Scientist', 'Engine', 'Shakespeare', 'Wind',
    'Kid', 'Embassy', 'Robot', 'Note', 'Ground', 'Draft', 'Ham', 'War', 'Mouse', 'Center', 'Chick', 'China', 'Bolt',
    'Spot', 'Piano', 'Pupil', 'Plot', 'Lion', 'Police', 'Head', 'Litter', 'Concert', 'Mug', 'Vacuum', 'Atlantis',
    'Straw', 'Switch', 'Skyscraper', 'Laser', 'Scuba Diver', 'Africa', 'Plastic', 'Dwarf', 'Lap', 'Life', 'Honey',
    'Horseshoe', 'Unicorn', 'Spy', 'Pants', 'Wall', 'Paper', 'Sound', 'Ice', 'Tag', 'Web', 'Fan', 'Orange', 'Temple',
    'Canada', 'Scorpion', 'Undertaker', 'Mail', 'Europe', 'Soul', 'Apple', 'Pole', 'Tap', 'Mouth', 'Ambulance', 'Dress',
    'Ice Cream', 'Rabbit', 'Buck', 'Agent', 'Sock', 'Nut', 'Boot', 'Ghost', 'Oil', 'Superhero', 'Code', 'Kiwi',
    'Hospital', 'Saturn', 'Film', 'Button', 'Snowman', 'Helicopter', 'Loch Ness', 'Log', 'Princess', 'Time', 'Cook',
    'Revolution', 'Shoe', 'Mole', 'Spell', 'Grass', 'Washer', 'Game', 'Beat', 'Hole', 'Horse', 'Pirate', 'Link',
    'Dance', 'Fly', 'Pit', 'Server', 'School', 'Lock', 'Brush', 'Pool', 'Star', 'Jam', 'Organ', 'Berlin', 'Face',
    'Luck', 'Amazon', 'Cast', 'Gas', 'Club', 'Sink', 'Water', 'Chair', 'Shark', 'Jupiter', 'Copper', 'Jack', 'Platypus',
    'Stick', 'Olive', 'Grace', 'Bear', 'Glass', 'Row', 'Pistol', 'London', 'Rock', 'Van', 'Vet', 'Beach', 'Charge',
    'Port', 'Disease', 'Palm', 'Moscow', 'Pin', 'Washington', 'Pyramid', 'Opera', 'Casino', 'Pilot', 'String', 'Night',
    'Chest', 'Yard', 'Teacher', 'Pumpkin', 'Thief', 'Bark', 'Bug', 'Mint', 'Cycle', 'Telescope', 'Calf', 'Air', 'Box',
    'Mount', 'Thumb', 'Antarctica', 'Trunk', 'Snow', 'Penguin', 'Root', 'Bar', 'File', 'Hawk', 'Battery', 'Compound',
    'Slug', 'Octopus', 'Whip', 'America', 'Ivory', 'Pound', 'Sub', 'Cliff', 'Lab', 'Eagle', 'Genius', 'Ship', 'Dice',
    'Hood', 'Heart', 'Novel', 'Pipe', 'Himalayas', 'Crown', 'Round', 'India', 'Needle', 'Shop', 'Watch', 'Lead', 'Tie',
    'Table', 'Cell', 'Cover', 'Czech', 'Back', 'Bomb', 'Ruler', 'Forest', 'Bottle', 'Space', 'Hook', 'Doctor', 'Ball',
    'Bow', 'Degree', 'Rome', 'Plane', 'Giant', 'Nail', 'Dragon', 'Stadium', 'Flute', 'Carrot', 'Wake', 'Fighter',
    'Model', 'Tokyo', 'Eye', 'Mexico', 'Hand', 'Swing', 'Key', 'Alien', 'Tower', 'Poison', 'Cricket', 'Cold', 'Knife',
    'Church', 'Board', 'Cloak', 'Ninja', 'Olympus', 'Belt', 'Light', 'Death', 'Stock', 'Millionaire', 'Day', 'Knight',
    'Pie', 'Bed', 'Circle', 'Rose', 'Change', 'Cap', 'Triangle',
];

export const wordsAlt = [
    'AFRICA', 'AGENT', 'AIR', 'ALIEN', 'ALPS', 'AMAZON', 'AMBULANCE', 'AMERICA', 'ANGEL', 'ANTARCTICA', 'APPLE', 'ARM',
    'ATLANTIS', 'AUSTRALIA', 'AZTEC', 'BACK', 'BALL', 'BAND', 'BANK', 'BAR', 'BARK', 'BAT', 'BATTERY', 'BEACH', 'BEAR',
    'BEAT', 'BED', 'BEIJING', 'BELL', 'BELT', 'BERLIN', 'BERMUDA', 'BERRY', 'BILL', 'BLOCK', 'BOARD', 'BOLT', 'BOMB',
    'BOND', 'BOOM', 'BOOT', 'BOTTLE', 'BOW', 'BOX', 'BRIDGE', 'BRUSH', 'BUCK', 'BUFFALO', 'BUG', 'BUGLE', 'BUTTON',
    'CALF', 'CANADA', 'CAP', 'CAPITAL', 'CAR', 'CARD', 'CARROT', 'CASINO', 'CAST', 'CAT', 'CELL', 'CENTAUR', 'CENTER',
    'CHAIR', 'CHANGE', 'CHARGE', 'CHECK', 'CHEST', 'CHICK', 'CHINA', 'CHOCOLATE', 'CHURCH', 'CIRCLE', 'CLIFF', 'CLOAK',
    'CLUB', 'CODE', 'COLD', 'COMIC', 'COMPOUND', 'CONCERT', 'CONDUCTOR', 'CONTRACT', 'COOK', 'COPPER', 'COTTON',
    'COURT', 'COVER', 'CRANE', 'CRASH', 'CRICKET', 'CROSS', 'CROWN', 'CYCLE', 'CZECH', 'DANCE', 'DATE', 'DAY', 'DEATH',
    'DECK', 'DEGREE', 'DIAMOND', 'DICE', 'DINOSAUR', 'DISEASE', 'DOCTOR', 'DOG', 'DRAFT', 'DRAGON', 'DRESS', 'DRILL',
    'DROP', 'DUCK', 'DWARF', 'EAGLE', 'EGYPT', 'EMBASSY', 'ENGINE', 'ENGLAND', 'EUROPE', 'EYE', 'FACE', 'FAIR', 'FALL',
    'FAN', 'FENCE', 'FIELD', 'FIGHTER', 'FIGURE', 'FILE', 'FILM', 'FIRE', 'FISH', 'FLUTE', 'FLY', 'FOOT', 'FORCE',
    'FOREST', 'FORK', 'FRANCE', 'GAME', 'GAS', 'GENIUS', 'GERMANY', 'GHOST', 'GIANT', 'GLASS', 'GLOVE', 'GOLD', 'GRACE',
    'GRASS', 'GREECE', 'GREEN', 'GROUND', 'HAM', 'HAND', 'HAWK', 'HEAD', 'HEART', 'HELICOPTER', 'HIMALAYAS', 'HOLE',
    'HOLLYWOOD', 'HONEY', 'HOOD', 'HOOK', 'HORN', 'HORSE', 'HORSESHOE', 'HOSPITAL', 'HOTEL', 'ICE', 'ICE', 'CREAM',
    'INDIA', 'IRON', 'IVORY', 'JACK', 'JAM', 'JET', 'JUPITER', 'KANGAROO', 'KETCHUP', 'KEY', 'KID', 'KING', 'KIWI',
    'KNIFE', 'KNIGHT', 'LAB', 'LAP', 'LASER', 'LAWYER', 'LEAD', 'LEMON', 'LEPRECHAUN', 'LIFE', 'LIGHT', 'LIMOUSINE',
    'LINE', 'LINK', 'LION', 'LITTER', 'LOCH', 'NESS', 'LOCK', 'LOG', 'LONDON', 'LUCK', 'MAIL', 'MAMMOTH', 'MAPLE',
    'MARBLE', 'MARCH', 'MASS', 'MATCH', 'MERCURY', 'MEXICO', 'MICROSCOPE', 'MILLIONAIRE', 'MINE', 'MINT', 'MISSILE',
    'MODEL', 'MOLE', 'MOON', 'MOSCOW', 'MOUNT', 'MOUSE', 'MOUTH', 'MUG', 'NAIL', 'NEEDLE', 'NET', 'NEW', 'YORK',
    'NIGHT', 'NINJA', 'NOTE', 'NOVEL', 'NURSE', 'NUT', 'OCTOPUS', 'OIL', 'OLIVE', 'OLYMPUS', 'OPERA', 'ORANGE', 'ORGAN',
    'PALM', 'PAN', 'PANTS', 'PAPER', 'PARACHUTE', 'PARK', 'PART', 'PASS', 'PASTE', 'PENGUIN', 'PHOENIX', 'PIANO', 'PIE',
    'PILOT', 'PIN', 'PIPE', 'PIRATE', 'PISTOL', 'PIT', 'PITCH', 'PLANE', 'PLASTIC', 'PLATE', 'PLATYPUS', 'PLAY', 'PLOT',
    'POINT', 'POISON', 'POLE', 'POLICE', 'POOL', 'PORT', 'POST', 'POUND', 'PRESS', 'PRINCESS', 'PUMPKIN', 'PUPIL',
    'PYRAMID', 'QUEEN', 'RABBIT', 'RACKET', 'RAY', 'REVOLUTION', 'RING', 'ROBIN', 'ROBOT', 'ROCK', 'ROME', 'ROOT',
    'ROSE', 'ROULETTE', 'ROUND', 'ROW', 'RULER', 'SATELLITE', 'SATURN', 'SCALE', 'SCHOOL', 'SCIENTIST', 'SCORPION',
    'SCREEN', 'SCUBA', 'DIVER', 'SEAL', 'SERVER', 'SHADOW', 'SHAKESPEARE', 'SHARK', 'SHIP', 'SHOE', 'SHOP', 'SHOT',
    'SINK', 'SKYSCRAPER', 'SLIP', 'SLUG', 'SMUGGLER', 'SNOW', 'SNOWMAN', 'SOCK', 'SOLDIER', 'SOUL', 'SOUND', 'SPACE',
    'SPELL', 'SPIDER', 'SPIKE', 'SPINE', 'SPOT', 'SPRING', 'SPY', 'SQUARE', 'STADIUM', 'STAFF', 'STAR', 'STATE',
    'STICK', 'STOCK', 'STRAW', 'STREAM', 'STRIKE', 'STRING', 'SUB', 'SUIT', 'SUPERHERO', 'SWING', 'SWITCH', 'TABLE',
    'TABLET', 'TAG', 'TAIL', 'TAP', 'TEACHER', 'TELESCOPE', 'TEMPLE', 'THEATER', 'THIEF', 'THUMB', 'TICK', 'TIE',
    'TIME', 'TOKYO', 'TOOTH', 'TORCH', 'TOWER', 'TRACK', 'TRAIN', 'TRIANGLE', 'TRIP', 'TRUNK', 'TUBE', 'TURKEY',
    'UNDERTAKER', 'UNICORN', 'VACUUM', 'VAN', 'VET', 'WAKE', 'WALL', 'WAR', 'WASHER', 'WASHINGTON', 'WATCH', 'WATER',
    'WAVE', 'WEB', 'WELL', 'WHALE', 'WHIP', 'WIND', 'WITCH', 'WORM', 'YARD',
];

export const wordsNL = [
    'POST', 'ROULETTE', 'DRAAK', 'OORLOG', 'HONING', 'BOM', 'CASINO', 'WOLKENKRABBER', 'SATURNUS', 'ASTRONAUT', 'ZWEEP',
    'ANTARCTICA', 'SNEEUWPOP', 'CONCERT', 'CHOCOLADE', 'VLIEGTUIG', 'MILJONAIR', 'DINOSAURUS', 'KAMELEON', 'TROMPET',
    'PINGUÏN', 'SPIN', 'RAKET', 'AMBASSADE', 'PISTOOL', 'ZIEKTE', 'SPION', 'PRINSES', 'GENIE', 'DIEF', 'OPERA', 'RIDDER',
    'STADION', 'LIMOUSINE', 'SPOOK', 'BUS', 'LOLLY', 'LASER', 'DOOD', 'ZIEKENHUIS', 'AMBULANCE', 'INKTVIS', 'HELIKOPTER',
    'KANGOEROE', 'MICROSCOOP', 'PRETPARK', 'SUPERHELD', 'TELESCOOP', 'PARACHUTE', 'VAMPIER', 'ROTONDE', 'SATELLIET',
    'ENGEL', 'ROBOT', 'EENHOORN', 'HEKS', 'KOLONIST', 'DUIKER', 'GIF', 'BRUG', 'VUUR', 'COBRA', 'WALVIS', 'MAAN', 'VIS',
    'DOKTER', 'KERK', 'PLEISTER', 'ZUSTER', 'WIND', 'LEEUW', 'OOG', 'LUCHT', 'KONIJN', 'BANK', 'GRAS', 'JURK', 'DWERG',
    'BOS', 'AUTO', 'HANDSCHOEN', 'APPEL', 'OLIE', 'KOK', 'BEER', 'POES', 'LEVEN', 'GELUK', 'REUS', 'SPIEGEL', 'STRAND',
    'HOTEL', 'WATER', 'PAPIER', 'WORM', 'ADVOCAAT', 'WETENSCHAPPER', 'DANS', 'WORTEL', 'KETCHUP', 'NACHT', 'KATOEN',
    'VOET', 'MUIS', 'MES', 'THEATER', 'AGENT', 'SCHIP', 'PILOOT', 'DUIM', 'LERAAR', 'FLES', 'DAG', 'KONING', 'GLAS',
    'KABEL', 'TAND', 'HOND', 'PAARD', 'SCHOEN', 'STOEL', 'KROON', 'IJS', 'GOUD', 'VORK', 'TIJD', 'FLUIT', 'VLAM',
    'SNEEUW', 'IVOOR', 'SOLDAAT', 'PIRAMIDE', 'KUBUS', 'STER', 'RING', 'HOORN', 'HART', 'BLOK', 'BUIS', 'NAALD', 'LIJN',
    'KRIJT', 'BORD', 'BOX', 'SCHERM', 'STUK', 'SPOT', 'KNOP', 'MOND', 'ETIKET', 'HAND', 'BED', 'MUUR', 'TOREN', 'KAART',
    'BAD', 'DIAMANT', 'KRUIS', 'NET', 'PUNT', 'NOOT', 'PLAAT', 'HOL', 'WIJZER', 'KRACHT', 'SLEUTEL', 'MACHINE',
    'OVERGANG', 'STROOM', 'HOOFD', 'PAAL', 'CENTRUM', 'ONGELUK', 'SCHAT', 'SLOT', 'CODE', 'CIRKEL', 'LINK', 'PIJP',
    'AMSTERDAM', 'NEDERLAND', 'LIMBURG', 'BRUSSEL', 'EGYPTE', 'LONDEN', 'CARNAVAL', 'ROTTERDAM', 'BELGIË', 'HUNEBED',
    'HOLLYWOOD', 'GRIEKENLAND', 'ROME', 'ARDENNEN', 'NINJA', 'POOL', 'SHOARMA', 'DUITSLAND', 'PROVINCIE', 'AMERIKA',
    'ATLANTIS', 'ENGELAND', 'LOEMPIA', 'AFRIKA', 'TABLET', 'FRANKRIJK', 'KLOMP', 'POLDER', 'EURO', 'VOETBAL', 'ZEELAND',
    'BERLIJN', 'PIZZA', 'DOLFIJN', 'HAWAÏ', 'MOTOR', 'LAARS', 'CARAVAN', 'FRIET', 'ALPEN', 'SEIZOEN', 'KAMER', 'BLIK',
    'VORST', 'IJZER', 'ZEGEL', 'LICHT', 'MARS', 'GROEN', 'JAM', 'EUROPA', 'LEIDING', 'WISSEL', 'AARDE', 'STRAAL',
    'DEKSEL', 'CITROEN', 'ROOS', 'TAFEL', 'STAART', 'METER', 'DIJK', 'BATTERIJ', 'ARENA', 'BEELD', 'KOSTUUM', 'SLANG',
    'SPOOR', 'GAREN', 'AANDEEL', 'VET', 'BLOND', 'SLIP', 'GEMEENTE', 'SLAG', 'PROEF', 'CLUB', 'SCHADUW', 'BENDE',
    'STRIP', 'TWEELING', 'BAND', 'CHIP', 'TOCHT', 'DUIKBOOT', 'MIJN', 'VINK', 'VLIEG', 'KOUD', 'KNIKKER', 'SPEL',
    'HAAK', 'KNUPPEL', 'KETTING', 'SCHEIDING', 'STAPEL', 'BAR', 'BUBBEL', 'POND', 'ROND', 'VELD', 'HEMEL', 'BOK',
    'VEER', 'ZINK', 'FIETS', 'SCHRIFT', 'MAT', 'SLEE', 'PATROON', 'GROND', 'RUG', 'STAM', 'MUNT', 'GRAAD', 'KEGEL',
    'UITZENDING', 'EIKEL', 'MOL', 'GESLACHT', 'TEMPEL', 'POMPOEN', 'IJSBEER', 'SMOKKELAAR', 'HAM', 'VLUCHT', 'KRUIK',
    'VAL', 'SPREUK', 'BOEK', 'RAAD', 'BAL', 'PIL', 'ELF', 'BUREAU', 'ARM', 'SCHAAL', 'FLITS', 'CEL', 'VULKAAN',
    'CONTRACT', 'CHINEES', 'BAAN', 'DIERENARTS', 'HAVEN', 'GOLF', 'NICHT', 'STEEK', 'MASKER', 'RIET', 'GELUID', 'PRIJS',
    'SCHROEF', 'HAVIK', 'PERS', 'FORMULE', 'AS', 'KUIP', 'VIOOL', 'REGEL', 'DICHT', 'MASSA', 'WEB', 'ZAK', 'PALM',
    'KRAAN', 'PASTA', 'TAART', 'GERECHT', 'SPIJKER', 'MODEL', 'WEEGSCHAAL', 'REVOLUTIE', 'PARIJS', 'GAS', 'SINGLE',
    'PIANO', 'BESTAND', 'BRON', 'PODIUM', 'AANVAL', 'ASIEL', 'NETWERK', 'WEDSTRIJD', 'FILM', 'SCHIJF', 'AMAZONE',
    'RUIMTE', 'BEURS', 'STAF', 'SHUTTLE', 'PIRAAT', 'KOP', 'STEM', 'GAT', 'KUSSEN', 'KAMP', 'TON', 'SPA', 'PAD',
    'FIGUUR', 'GEZICHT', 'DOOS', 'NAGEL', 'PINDA', 'MONSTER', 'WAS', 'RECEPT', 'TOETS', 'TAP', 'SCHOOL', 'TROMMEL',
    'KEVER', 'KATER', 'TANK', 'KOPER', 'SCHOT', 'HAGEL', 'RIEM', 'PUPIL', 'ORANJE', 'DOEL', 'FOXTROT', 'RACKET',
    'DRAAI', 'RACE', 'MAAT', 'HORDE', 'SAMBA', 'DIPLOMA', 'SALSA', 'RECORD', 'VLOER', 'TEAM', 'RITME', 'BASKET',
    'DISCO', 'ATLETIEK', 'BALLET', 'TRAINER', 'CHOREOGRAAF', 'AMBER', 'ZOUT', 'LAVENDEL', 'HEET', 'ZWART', 'WORST',
    'BLANK', 'KOFFIE', 'JASMIJN', 'TONG', 'MARINE', 'SPEK', 'GRIJS', 'BELEG', 'ZILVER', 'CHILI', 'ZALM', 'SCHUIM',
];
