export const words = [
  'Sahajanand', 'Harikrushna', 'Nilkanth', 'Swaminarayan', 'Sarjudas', 'Ghanshyam', 'Narayanmuni', 'Hari',
  'Premanand', 'Muktanand', 'Brahmanand', 'Shukanand', 'Gopalanand', 'Gunatitanand', 'Nishkulanand', 'Nityanand', 'Atmanand', 'Adbhutanand', 'Sachidanand',
  'Raguvirprasad', 'Ayodhyaprasad', 'Dharmadev', 'Bhaktimata', 'IchchhaRam', 'Rampratap', 'Suvasani Bhabhi',
  'Vadtal', 'Ahmedabad', 'Gadhpur', 'Chhapaiya', 'Junagadh', 'Dholera', 'Bhuj', 
  'Bhadra', 'Fareni', 'Idar Todla', 'Amrapur, Amreli', 'Karyani', 'Sarangpur', 'Mangrol', 'Jetpur', 'Gondal', 'Loej', 'Panchala', 'Kalvani', 'Sardhar', 'Rajkot', 'Surat', 
  'Parvatbhai', 'Dada Khachar', 'Jivu Ba', 'Joban Pagi', 'Pachu Ba', 'Jinabhai', 'Sir Malkam', 'Uka Khachar', 'Sura Khachar',
  'Unmat Ganga', 'Manorama', 'Narmada', 'Ganga', 'Yamuna', 'Saryu', 
  'Badrinath', 'Mathura', 'Dwarka', 'Ayodhya', 'Rameshwaram', 'Jagganath', 'Burhanpur', 'Kashi', 'Kedarnath', 
  'Ramanand', 'Valbhacharya', 'Ramanujacharya', 'Uddhavji', 'Ved Vyas',
  'Gopinathji', 'NarNarayan', 'LaxmiNarayan', 'Madan Mohan', 'Radha Raman', 'Ranchod Trikam', 'Surya Narayan', 
  'Shikshapatri', 'Vachnamrut', 'Ghanshyam Lilaamrut', 'Satsangi Jivan', 'Swami Ni Vato', 'Bhaktachintamani', 'Purshotam Prakash', 'Chosath Padi',
  'Krishna', 'Ram', 'Kapil Dev', 'Vaman',  'Nurshi',
  'Hanuman', 'Mahadev', 'Parvatiji', 'Ganpati', 
  'Jad-Bharat', 'Sita', 'Narad', 'Dhruv', 'Prahlad', 'Narshi Mehta', 
  'Arjun', 'Dhraupadi', 'Abhimanyu', 'Ekalavya', 'Balram', 'Kunti', 'Drona', 'Bhishma', 'Pandu Raja', 'Bhim', 'Yudhisthir', 'Nakul',
];