export const words = [
  'Sahajanand', 'Harikrushna', 'Nilkanth', 'Swaminarayan', 'Sarjudas',
  'Premanand', 'Muktanand', 'Brahmanand', 'Shukanand', 'Gopalanand', 'Gunatitanand', 'Nishkulanand', 'Nityanand', 'Atmanand', 'Adbhutanand', 'Sachianand',
  'Raguvirprasad', 'Ayodhyaprasad', 'Dharmadev', 'Bhaktimata', 'IcchaRam', 'Rampratap', 'Suhasani Bhabhi',
  'Vadtal', 'Ahmedabad', 'Gadhpur', 'Chappiya', 'Junagadh', 'Dholera', 'Bhuj', 
  'Bhadra', 'Fareni', 'Idar Todla', 'Amrapur, Amreli', 'Karyani', 'Sarangpur', 'Mangrod', 'Jetpur', 'Gondal', 'Loej', 'Panchala', 'Kalvani', 'Sardhar', 'Rajkot', 'Surat', 
  'Parvatbhai', 'Dada Khachar', 'Jivu Ba', 'Joban Pagi', 'Pachu Ba', 'Jinabhai', 'Sir Malkam',
  'Unmat Ganga', 'Manorama', 'Narmada', 'Ganga', 'Yamuna',
  'Badrinath', 'Mathura', 'Dwarka', 'Ayodhya', 'Rameshwaram', 'Jagganath', 'Buranpur', 'Kashi',
  'Ramanand', 'Valbhacharya', 'Ramanuacharya', 'Uddhavji', 'Ved Vyas',
  'Gopinathji', 'NarNarayan', 'LaxmiNarayan', 'Madan Mohan', 'Radha Raman', 'Ranchod Trikam', 'Surya Narayan', 
  'Shikshapatri', 'Vachnamrut', 'Ghanshyam Lilaamrut', 'Satsangi Jivan', 'Swami Ni Vato', 'Bhaktachintamani', 'Purshotam Prakash', 'Chosath Padi',
  'Krishna', 'Ram', 'Kapil Dev', 'Vaman',  'Nurshi',
  'Hanuman', 'Mahadev', 'Parvatiji', 'Ganpati', 
  'Jad-Bharat', 'Sita', 'Narad', 'Dhruv', 'Prahlad', 'Narshi Mehta', 
  'Arjun', 'Dhraupadi', 'Abhimanyu', 'Ekalavya', 'Balram', 'Kunti', 'Drona', 'Bhishma', 'Pandu Raja', 'Bhim', 'Yudhisthir', 'Nakul',
];