export const GRID_SIZE = 5;
export const COL_DELTA = 15;
export const TIME_OUT = 8000; // time in ms (reduced from 10000 for better game pacing)
export const TIME_BUFF = 1000; // time in ms
export const WILDCARD_NUM = -100;
export const INITIAL_WAIT_REF_NUM = -1;
export const INITIAL_WAIT_TIME = TIME_OUT; // for now same, but can be adapted as needed
export const BACKOFF_INTERVAL = 500; // reduced from 1500 for faster number progression
export const MAX_BACKOFF_CANDIDATES = 5;
export const CALL_BOX_SIZE = 2;
export const STROKE_WIDTH = 0.125 / GRID_SIZE;
export const MAX_BINGO_CALLS = 3;
