export const GRID_SIZE = 5;
export const COL_DELTA = 15;
export const TIME_OUT = 5000; // time in ms
export const TIME_BUFF = 1000; // time in ms
export const WILDCARD_NUM = -100;
export const INITIAL_WAIT_REF_NUM = -1;
export const INITIAL_WAIT_TIME = TIME_OUT; // for now same, but can be adapted as needed
export const BACKOFF_INTERVAL = 500;
export const MAX_BACKOFF_CANDIDATES = 5;
export const CALL_BOX_SIZE = 2;
export const STROKE_WIDTH = 0.125 / GRID_SIZE;
export const MAX_BINGO_CALLS = 3;
