export const GRID_SIZE = 5;
export const COL_DELTA = 15;
export const TIME_OUT = 3;
export const TIME_BUFF = 1;
export const WILDCARD_NUM = -100;
export const WAIT_MSG_NUMBER = -1;
export const CALL_BOX_SIZE = 2;
export const STROKE_WIDTH = 0.125 / GRID_SIZE;
export const MAX_BINGO_CALLS = 3;
