import { Suit } from 'gamesShared/definitions/cards';

export enum cardEnum {
  SA,
  S2,
  S3,
  S4,
  S5,
  S6,
  S7,
  S8,
  S9,
  S10,
  SJ,
  SQ,
  SK,
  CA,
  C2,
  C3,
  C4,
  C5,
  C6,
  C7,
  C8,
  C9,
  C10,
  CJ,
  CQ,
  CK,
  DA,
  D2,
  D3,
  D4,
  D5,
  D6,
  D7,
  D8,
  D9,
  D10,
  DJ,
  DQ,
  DK,
  HA,
  H2,
  H3,
  H4,
  H5,
  H6,
  H7,
  H8,
  H9,
  H10,
  HJ,
  HQ,
  HK,
  GB,
}

export const deckAssets = {
  [cardEnum.SA]: { suit: Suit.Spades, value: 1 },
  [cardEnum.S2]: { suit: Suit.Spades, value: 2 },
  [cardEnum.S3]: { suit: Suit.Spades, value: 3 },
  [cardEnum.S4]: { suit: Suit.Spades, value: 4 },
  [cardEnum.S5]: { suit: Suit.Spades, value: 5 },
  [cardEnum.S6]: { suit: Suit.Spades, value: 6 },
  [cardEnum.S7]: { suit: Suit.Spades, value: 7 },
  [cardEnum.S8]: { suit: Suit.Spades, value: 8 },
  [cardEnum.S9]: { suit: Suit.Spades, value: 9 },
  [cardEnum.S10]: { suit: Suit.Spades, value: 10 },
  [cardEnum.SJ]: { suit: Suit.Spades, value: 11 },
  [cardEnum.SQ]: { suit: Suit.Spades, value: 12 },
  [cardEnum.SK]: { suit: Suit.Spades, value: 13 },
  [cardEnum.CA]: { suit: Suit.Clubs, value: 1 },
  [cardEnum.C2]: { suit: Suit.Clubs, value: 2 },
  [cardEnum.C3]: { suit: Suit.Clubs, value: 3 },
  [cardEnum.C4]: { suit: Suit.Clubs, value: 4 },
  [cardEnum.C5]: { suit: Suit.Clubs, value: 5 },
  [cardEnum.C6]: { suit: Suit.Clubs, value: 6 },
  [cardEnum.C7]: { suit: Suit.Clubs, value: 7 },
  [cardEnum.C8]: { suit: Suit.Clubs, value: 8 },
  [cardEnum.C9]: { suit: Suit.Clubs, value: 9 },
  [cardEnum.C10]: { suit: Suit.Clubs, value: 10 },
  [cardEnum.CJ]: { suit: Suit.Clubs, value: 11 },
  [cardEnum.CQ]: { suit: Suit.Clubs, value: 12 },
  [cardEnum.CK]: { suit: Suit.Clubs, value: 13 },
  [cardEnum.DA]: { suit: Suit.Diamonds, value: 1 },
  [cardEnum.D2]: { suit: Suit.Diamonds, value: 2 },
  [cardEnum.D3]: { suit: Suit.Diamonds, value: 3 },
  [cardEnum.D4]: { suit: Suit.Diamonds, value: 4 },
  [cardEnum.D5]: { suit: Suit.Diamonds, value: 5 },
  [cardEnum.D6]: { suit: Suit.Diamonds, value: 6 },
  [cardEnum.D7]: { suit: Suit.Diamonds, value: 7 },
  [cardEnum.D8]: { suit: Suit.Diamonds, value: 8 },
  [cardEnum.D9]: { suit: Suit.Diamonds, value: 9 },
  [cardEnum.D10]: { suit: Suit.Diamonds, value: 10 },
  [cardEnum.DJ]: { suit: Suit.Diamonds, value: 11 },
  [cardEnum.DQ]: { suit: Suit.Diamonds, value: 12 },
  [cardEnum.DK]: { suit: Suit.Diamonds, value: 13 },
  [cardEnum.HA]: { suit: Suit.Hearts, value: 1 },
  [cardEnum.H2]: { suit: Suit.Hearts, value: 2 },
  [cardEnum.H3]: { suit: Suit.Hearts, value: 3 },
  [cardEnum.H4]: { suit: Suit.Hearts, value: 4 },
  [cardEnum.H5]: { suit: Suit.Hearts, value: 5 },
  [cardEnum.H6]: { suit: Suit.Hearts, value: 6 },
  [cardEnum.H7]: { suit: Suit.Hearts, value: 7 },
  [cardEnum.H8]: { suit: Suit.Hearts, value: 8 },
  [cardEnum.H9]: { suit: Suit.Hearts, value: 9 },
  [cardEnum.H10]: { suit: Suit.Hearts, value: 10 },
  [cardEnum.HJ]: { suit: Suit.Hearts, value: 11 },
  [cardEnum.HQ]: { suit: Suit.Hearts, value: 12 },
  [cardEnum.HK]: { suit: Suit.Hearts, value: 13 },
  [cardEnum.GB]: null,
};

export const std_crib_deck = [
  { id: cardEnum.SA, faced: false, rank: cardEnum.SA },
  { id: cardEnum.S2, faced: false, rank: cardEnum.S2 },
  { id: cardEnum.S3, faced: false, rank: cardEnum.S3 },
  { id: cardEnum.S4, faced: false, rank: cardEnum.S4 },
  { id: cardEnum.S5, faced: false, rank: cardEnum.S5 },
  { id: cardEnum.S6, faced: false, rank: cardEnum.S6 },
  { id: cardEnum.S7, faced: false, rank: cardEnum.S7 },
  { id: cardEnum.S8, faced: false, rank: cardEnum.S8 },
  { id: cardEnum.S9, faced: false, rank: cardEnum.S9 },
  { id: cardEnum.S10, faced: false, rank: cardEnum.S10 },
  { id: cardEnum.SJ, faced: false, rank: cardEnum.SJ },
  { id: cardEnum.SQ, faced: false, rank: cardEnum.SQ },
  { id: cardEnum.SK, faced: false, rank: cardEnum.SK },
  { id: cardEnum.CA, faced: false, rank: cardEnum.CA },
  { id: cardEnum.C2, faced: false, rank: cardEnum.C2 },
  { id: cardEnum.C3, faced: false, rank: cardEnum.C3 },
  { id: cardEnum.C4, faced: false, rank: cardEnum.C4 },
  { id: cardEnum.C5, faced: false, rank: cardEnum.C5 },
  { id: cardEnum.C6, faced: false, rank: cardEnum.C6 },
  { id: cardEnum.C7, faced: false, rank: cardEnum.C7 },
  { id: cardEnum.C8, faced: false, rank: cardEnum.C8 },
  { id: cardEnum.C9, faced: false, rank: cardEnum.C9 },
  { id: cardEnum.C10, faced: false, rank: cardEnum.C10 },
  { id: cardEnum.CJ, faced: false, rank: cardEnum.CJ },
  { id: cardEnum.CQ, faced: false, rank: cardEnum.CQ },
  { id: cardEnum.CK, faced: false, rank: cardEnum.CK },
  { id: cardEnum.DA, faced: false, rank: cardEnum.DA },
  { id: cardEnum.D2, faced: false, rank: cardEnum.D2 },
  { id: cardEnum.D3, faced: false, rank: cardEnum.D3 },
  { id: cardEnum.D4, faced: false, rank: cardEnum.D4 },
  { id: cardEnum.D5, faced: false, rank: cardEnum.D5 },
  { id: cardEnum.D6, faced: false, rank: cardEnum.D6 },
  { id: cardEnum.D7, faced: false, rank: cardEnum.D7 },
  { id: cardEnum.D8, faced: false, rank: cardEnum.D8 },
  { id: cardEnum.D9, faced: false, rank: cardEnum.D9 },
  { id: cardEnum.D10, faced: false, rank: cardEnum.D10 },
  { id: cardEnum.DJ, faced: false, rank: cardEnum.DJ },
  { id: cardEnum.DQ, faced: false, rank: cardEnum.DQ },
  { id: cardEnum.DK, faced: false, rank: cardEnum.DK },
  { id: cardEnum.HA, faced: false, rank: cardEnum.HA },
  { id: cardEnum.H2, faced: false, rank: cardEnum.H2 },
  { id: cardEnum.H3, faced: false, rank: cardEnum.H3 },
  { id: cardEnum.H4, faced: false, rank: cardEnum.H4 },
  { id: cardEnum.H5, faced: false, rank: cardEnum.H5 },
  { id: cardEnum.H6, faced: false, rank: cardEnum.H6 },
  { id: cardEnum.H7, faced: false, rank: cardEnum.H7 },
  { id: cardEnum.H8, faced: false, rank: cardEnum.H8 },
  { id: cardEnum.H9, faced: false, rank: cardEnum.H9 },
  { id: cardEnum.H10, faced: false, rank: cardEnum.H10 },
  { id: cardEnum.HJ, faced: false, rank: cardEnum.HJ },
  { id: cardEnum.HQ, faced: false, rank: cardEnum.HQ },
  { id: cardEnum.HK, faced: false, rank: cardEnum.HK },
];

export const dealCribbage = {
  pattern: { players: 2, increment: 1, hand: 6 },
  setup: {
    count: 0,
    deck: [],
    hands: {
      north: { playerId: 'Player 1', private: [], melds: [], tricks: [], played: [] },
      east: { playerId: 'Player 2', private: [], melds: [], tricks: [], played: [] },
      south: { playerId: 'Player 3', private: [], melds: [], tricks: [], played: [] },
      west: { playerId: 'Player 4', private: [], melds: [], tricks: [], played: [] },
    },
    stock: [],
  },
  fresh: std_crib_deck,
  turn: false,
};
