#!/bin/bash

log() {
  echo $1
  curl -H "Content-Type: application/json" -d "{\"content\":\"$1\"}" $WEBHOOK
}
cd secrets
git pull || { echo "SECRETS GIT PULL FAILED, EXITING"; exit 1; }
cd ..
cd fbg-prod
git pull || { echo "FBG GIT PULL FAILED, EXITING"; exit 1; }
kubectl config use-context do-sfo3-fbg-k8s2 || exit 1
log "Found new FBG version, pushing to production..."
helm upgrade -f ../secrets/values.prod.yaml fbg ./helm || { log "Helm upgrade failed"; exit 1; }
./docker-build.sh -d || { log "Updating dependencies failed"; exit 1; }
./docker-build.sh -b || { log "Building docker images failed"; exit 1; }
./docker-build.sh -p || { log "Pushing images failed"; exit 1; }
kubectl rollout restart deployment fbg-web fbg-fbg-server fbg-bgio || { log "Rollout failed"; exit 1; }
log "Success! Changes should be live in minutes"
docker system prune --volumes -f
